require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BnbsController do

  # This should return the minimal set of attributes required to create a valid
  # Bnb. As you add validations to Bnb, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BnbsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bnbs as @bnbs" do
      bnb = Bnb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bnbs).should eq([bnb])
    end
  end

  describe "GET show" do
    it "assigns the requested bnb as @bnb" do
      bnb = Bnb.create! valid_attributes
      get :show, {:id => bnb.to_param}, valid_session
      assigns(:bnb).should eq(bnb)
    end
  end

  describe "GET othernew" do
    it "assigns a othernew bnb as @bnb" do
      get :othernew, {}, valid_session
      assigns(:bnb).should be_a_new(Bnb)
    end
  end

  describe "GET edit" do
    it "assigns the requested bnb as @bnb" do
      bnb = Bnb.create! valid_attributes
      get :edit, {:id => bnb.to_param}, valid_session
      assigns(:bnb).should eq(bnb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a othernew Bnb" do
        expect {
          post :create, {:bnb => valid_attributes}, valid_session
        }.to change(Bnb, :count).by(1)
      end

      it "assigns a newly created bnb as @bnb" do
        post :create, {:bnb => valid_attributes}, valid_session
        assigns(:bnb).should be_a(Bnb)
        assigns(:bnb).should be_persisted
      end

      it "redirects to the created bnb" do
        post :create, {:bnb => valid_attributes}, valid_session
        response.should redirect_to(Bnb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bnb as @bnb" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bnb.any_instance.stub(:save).and_return(false)
        post :create, {:bnb => {}}, valid_session
        assigns(:bnb).should be_a_new(Bnb)
      end

      it "re-renders the 'othernew' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bnb.any_instance.stub(:save).and_return(false)
        post :create, {:bnb => {}}, valid_session
        response.should render_template("othernew")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bnb" do
        bnb = Bnb.create! valid_attributes
        # Assuming there are no other bnbs in the database, this
        # specifies that the Bnb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bnb.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bnb.to_param, :bnb => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bnb as @bnb" do
        bnb = Bnb.create! valid_attributes
        put :update, {:id => bnb.to_param, :bnb => valid_attributes}, valid_session
        assigns(:bnb).should eq(bnb)
      end

      it "redirects to the bnb" do
        bnb = Bnb.create! valid_attributes
        put :update, {:id => bnb.to_param, :bnb => valid_attributes}, valid_session
        response.should redirect_to(bnb)
      end
    end

    describe "with invalid params" do
      it "assigns the bnb as @bnb" do
        bnb = Bnb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bnb.any_instance.stub(:save).and_return(false)
        put :update, {:id => bnb.to_param, :bnb => {}}, valid_session
        assigns(:bnb).should eq(bnb)
      end

      it "re-renders the 'edit' template" do
        bnb = Bnb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bnb.any_instance.stub(:save).and_return(false)
        put :update, {:id => bnb.to_param, :bnb => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bnb" do
      bnb = Bnb.create! valid_attributes
      expect {
        delete :destroy, {:id => bnb.to_param}, valid_session
      }.to change(Bnb, :count).by(-1)
    end

    it "redirects to the bnbs list" do
      bnb = Bnb.create! valid_attributes
      delete :destroy, {:id => bnb.to_param}, valid_session
      response.should redirect_to(bnbs_url)
    end
  end

end
